### PR TITLE
header: Hamburge, active link underline and logo added

### PR DESCRIPTION
**Pull request by Ellipticamit**
## Description

Header enhancement . Added Hamburger, Logo and  responsive menu.

## Issue

Issue/<#22>

### CODE REVIEW

**Review by ANDREYDEN — CHANGES_REQUESTED** [review]
Great work! A few corrections:
- I believe you can use the `favicon_GDSC.png` instead of the `logo_GDSC.png` (you can rename it to `logo.png` so it's generic
- It would be nice if the mobile menu would automatically close after picking an option
- I rate the effort with custom transitions on the hamburger icons, but I would appreciate it if we can stick to material UI [icons](https://fonts.google.com/icons?icon.query=close) as they match the overall Google theme better
- please make sure you use `npm` as this is an `npm` project (I noticed the `yarn.lock` file)

**Comment by ANDREYDEN** [comment]
@Ellipticamit, any progress on this?

**Comment by Ellipticamit** [comment]
@ANDREYDEN All issue mentioned above are resolved you can test now. If needs any further changes let me know.

**Review by ANDREYDEN — APPROVED** [review]
Looks good!

**Pull request merged**
