### PR TITLE
imported and set font to google open sans

### LINKED ISSUE #15: Set up fonts
We should be using Google Sans as a default font for all content

### PR DESCRIPTION
**Pull request by ifefrost**
## Description

I imported the online link to the open sans google font and then set it as the default root font for the site

## Issue

This PR fixes #15

### CODE REVIEW

**Review by ANDREYDEN — CHANGES_REQUESTED** [review]
Everythings good, but we need a different font: it's not Open Sans, but [Google Sans](https://www.cufonfonts.com/font/google-sans)

P. S. see if that link works, otherwise I'm going to send you some ttfs

**Comment by ifefrost** [comment]
Alright, I have made the changes.

**Comment by ANDREYDEN** [comment]
@ifefrost, nice work! Looks like your changes confict with the `master` branch - make sure to resolve the conflicts and request my review when you are ready:
image

**Review by ANDREYDEN — CHANGES_REQUESTED** [review]
Everything is good, just one thing to change: the `ComingSoon.css` has some custom fonts specified that override the global ones, let's get rid of that so that all text is consistent.

I also realize now that having everything as Google Sans isn't very readable - for example [Firebase docs](https://firebase.google.com/docs/build) use Google Sans for titles and Open Sans / Roboto for other text. Nothing to worry about in this PR, but I'll address this in a separate issue

**Review by ANDREYDEN — APPROVED** [review]
Ship it

**Pull request merged**
